### PR TITLE
Resolve hat path when applying a hat

### LINKED ISSUE #178: Error when applying a default hat
```2019-05-22 21:19:40 INFO        running docker build --network=host -t cdr_sshcode -f /home/robert/projects/cdr/sshcode/.sail/Dockerfile /home/robert/projects/cdr/sshcode --label com.coder.sail.base_image=cdr_sshcode
Sending build context to Docker daemon  1.594MB
Step 1/4 : FROM codercom/ubuntu-dev-go
 ---> ddfa4fb9d5f6
Step 2/4 : ENV GO111MODULE=off
 ---> Using cache
 ---> 39381396c7e9
Step 3/4 : LABEL project_root "~/go/src/go.coder.com"
 ---> Using cache
 ---> eec6921916cf
Step 4/4 : LABEL com.coder.sail.base_image=cdr_sshcode
 ---> Using cache
 ---> 38bf6ed2e25f
Successfully built 38bf6ed2e25f
Successfully tagged cdr_sshcode:latest
2019-05-22 21:19:41 INFO        using repo image cdr_sshcode
2019-05-22 21:19:41 INFO        writing sail proxy logs to /tmp/sailproxy_cdr_sshcode985088096
2019-05-22 21:19:41 ERROR       build run failed: failed to run container: failed to inspect image: Error: No such image: 
2019-05-22 21:19:41 ERROR       failed to remove cdr_sshcode
```

I have a default hat set which is below: 

```
FROM ubuntu

RUN sudo apt install zsh
RUN chsh user -s $(which zsh)

LABEL share.zsh="~/.zshrc:~/.zshrc"
```

This is very similar to the example provided for [fish](https://github.com/cdr/sail/tree/master/hat-examples/fish). Not sure if I am doing something wrong.

sail.toml file:
```
# sail configuration.
# default_image is the default Docker image to use if the repository provides none.
default_image = "codercom/ubuntu-dev"

# project_root is the base from which projects are mounted.
# projects are stored in directories with form "<root>/<org>/<repo>"
project_root = "~/projects"

# default hat lets you configure a hat that's applied automatically by default.
default_hat = "~/sail"

# default schema used to clone repo in sail run if none given
default_schema = "ssh"

# default host used to clone repo in sail run if none given
default_host = "github.com"
```

~/sail directory
image

### PR DESCRIPTION
**Pull request by nathanpotter**
resolves #178

### CODE REVIEW

File: runcmd.go [hunk 1]
```diff
@@ -248,6 +248,9 @@ func (c *runcmd) build(gf *globalFlags, proj *project, b *hatBuilder, r *runner)
 	image := b.baseImage
 	if b.hatPath != "" {
 		image, err = b.applyHat()
+		if err != nil {
+			return err
```
Comment (roberthmiller) [inline runcmd.go]: can this be moved outside of the other if?

Comment (nathanpotter) [reply runcmd.go]: I don't think so, this keeps it clear that the error check if for the `b.applyHat()` operation
