### PR TITLE
FIXES #201 Sail browser extension docker not found error on MacOS

### LINKED ISSUE #201: chrome extension: failed to run `docker info`
I think that we should better display that sail failed to start. Currently, the popup window (black terminal in browser) opens/displays the text/exits without me being able to fully note the error. Not sure that should be the expected behavior. 

Edit:
As a note, on MacOS, this is a problem. On my Linux machine, sail runs beautifully.

### PR DESCRIPTION
**Pull request by dougnukem**
FIXES #201 chrome extension: failed to run `docker info`

On MacOS when Chrome is launched from Finder (as opposed to from terminal/shell session) the `$PATH` environment variable does not contain `/usr/local/bin` which is the common location for docker to be installed.

This PR adds in `/usr/local/bin` to be included in the PATH env variable on MacOS `darwin`.

See similar issues with other browser extensions that rely on Go to execute commands on the user's path:

browserpass/browserpass-legacy#13
browserpass/browserpass-legacy#159

### CODE REVIEW

File: globalflags.go [hunk 1]
```diff
@@ -37,6 +39,15 @@ func (gf *globalFlags) config() config {
 
 // ensureDockerDaemon verifies that Docker is running.
 func (gf *globalFlags) ensureDockerDaemon() {
+	if runtime.GOOS == "darwin" {
+		path := os.Getenv("PATH")
+		localBin := "/usr/local/bin"
+		if !strings.Contains(path, localBin) {
+			sep := fmt.Sprintf("%c", os.PathListSeparator)
+			// Fix for MacOS to include /usr/local/bin where docker is commonly installed which is not included in $PATH when sail is launched by browser that was opened in Finder
```
Comment (deansheather) [inline globalflags.go]:
```suggestion
```

File: globalflags.go [hunk 2]
```diff
@@ -37,6 +39,15 @@ func (gf *globalFlags) config() config {
 
 // ensureDockerDaemon verifies that Docker is running.
 func (gf *globalFlags) ensureDockerDaemon() {
+	if runtime.GOOS == "darwin" {
```
Comment (deansheather) [inline globalflags.go]:
```suggestion
	// docker is installed in /usr/local/bin on MacOS, but this isn't in
	// $PATH when launched by a browser that was opened via Finder.
	if runtime.GOOS == "darwin" {
```

**Review by deansheather — APPROVED** [review]

**Comment by dougnukem** [comment]
@deansheather accepted PR suggestions
